global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'lms-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'lms-background-services'
    static_configs:
      - targets: ['background-services:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'aspire-dashboard'
    static_configs:
      - targets: ['aspire-dashboard:18888']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'sql-server'
    static_configs:
      - targets: ['sqlserver:1433']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s